// GTM Report display — parses AI markdown into grouped section cards
"use client";

import { useMemo } from "react";
import { motion } from "framer-motion";
import { RefreshCw, CheckCircle2 } from "lucide-react";
import CopyButton from "./CopyButton";
import DownloadButton from "./DownloadButton";
import ReportSection from "./ReportSection";

interface GTMReportProps {
  markdown: string;
  onRegenerate: () => void;
}

interface ParsedSection {
  title: string;
  content: string;
  index: number;
}

interface SectionGroup {
  label: string;
  color: string;
  dot: string;
  indices: number[]; // 1-based section numbers
}

const SECTION_GROUPS: SectionGroup[] = [
  {
    label: "Market Strategy",
    color: "text-blue-600",
    dot: "bg-blue-500",
    indices: [1, 2, 3, 4, 5],
  },
  {
    label: "Messaging & Positioning",
    color: "text-violet-600",
    dot: "bg-violet-500",
    indices: [6, 7, 8, 9, 11],
  },
  {
    label: "Sales & Outreach Assets",
    color: "text-amber-600",
    dot: "bg-amber-500",
    indices: [12, 13, 14, 15],
  },
  {
    label: "Commercial & Action Plan",
    color: "text-emerald-600",
    dot: "bg-emerald-500",
    indices: [10, 16],
  },
];

function parseMarkdownSections(markdown: string): ParsedSection[] {
  const lines = markdown.split("\n");
  const sections: ParsedSection[] = [];
  let currentTitle = "";
  let currentLines: string[] = [];
  let sectionIndex = 0;

  for (const line of lines) {
    if (line.startsWith("## ")) {
      if (currentTitle && currentLines.length > 0) {
        sections.push({
          title: currentTitle,
          content: currentLines.join("\n").trim(),
          index: sectionIndex,
        });
      }
      const match =
        line.match(/^##\s+\d+\.\s+(.+)$/) || line.match(/^##\s+(.+)$/);
      sectionIndex++;
      currentTitle = match ? match[1].trim() : line.replace("## ", "").trim();
      currentLines = [];
    } else if (currentTitle) {
      currentLines.push(line);
    }
  }

  if (currentTitle && currentLines.length > 0) {
    sections.push({
      title: currentTitle,
      content: currentLines.join("\n").trim(),
      index: sectionIndex,
    });
  }

  return sections;
}

export default function GTMReport({ markdown, onRegenerate }: GTMReportProps) {
  const sections = useMemo(() => parseMarkdownSections(markdown), [markdown]);

  // Build a map: 1-based index → section
  const sectionByIndex = useMemo(() => {
    const map = new Map<number, ParsedSection>();
    sections.forEach((s) => map.set(s.index, s));
    return map;
  }, [sections]);

  return (
    <div className="space-y-3">
      {/* Report toolbar */}
      <div className="bg-white border border-slate-200 rounded-xl px-5 py-3.5 flex flex-col sm:flex-row sm:items-center justify-between gap-3">
        <div className="flex items-center gap-3">
          <div className="w-7 h-7 rounded-full bg-emerald-100 flex items-center justify-center flex-shrink-0">
            <CheckCircle2 className="h-4 w-4 text-emerald-600" />
          </div>
          <div>
            <div className="flex items-center gap-2">
              <h2 className="text-sm font-semibold text-slate-900">
                GTM Pack Ready
              </h2>
              <span className="text-[11px] font-medium text-emerald-600 bg-emerald-50 border border-emerald-100 px-1.5 py-0.5 rounded-full">
                {sections.length} sections
              </span>
            </div>
            <p className="text-[11px] text-slate-400 mt-0.5">
              Generated by FinGTM Agent · Powered by DeepSeek · For strategic reference only
            </p>
          </div>
        </div>
        <div className="flex items-center gap-2 flex-wrap flex-shrink-0">
          <CopyButton text={markdown} label="Copy Report" />
          <DownloadButton content={markdown} filename="fingtm-report.md" />
          <button
            onClick={onRegenerate}
            className="inline-flex items-center gap-1.5 px-3 py-1.5 text-[12px] font-medium rounded-md border border-slate-200 bg-white text-slate-600 hover:bg-slate-50 hover:border-slate-300 transition-colors"
          >
            <RefreshCw className="h-3.5 w-3.5" />
            Regenerate
          </button>
        </div>
      </div>

      {/* Grouped section cards */}
      {sections.length > 0 ? (
        <div className="space-y-5">
          {SECTION_GROUPS.map((group) => {
            const groupSections = group.indices
              .map((idx) => sectionByIndex.get(idx))
              .filter((s): s is ParsedSection => s !== undefined);

            if (groupSections.length === 0) return null;

            return (
              <div key={group.label}>
                {/* Group header */}
                <div className="flex items-center gap-2 mb-2 px-1">
                  <span className={`w-2 h-2 rounded-full flex-shrink-0 ${group.dot}`} />
                  <span className={`text-[11px] font-bold uppercase tracking-widest ${group.color}`}>
                    {group.label}
                  </span>
                  <span className="flex-1 h-px bg-slate-200" />
                  <span className="text-[10px] text-slate-400">
                    {groupSections.length} section{groupSections.length !== 1 ? "s" : ""}
                  </span>
                </div>

                <div className="space-y-2">
                  {groupSections.map((section, i) => {
                    // Compute global position for staggered animation
                    const globalI =
                      SECTION_GROUPS.slice(
                        0,
                        SECTION_GROUPS.indexOf(group)
                      ).reduce((acc, g) => acc + g.indices.length, 0) + i;

                    return (
                      <motion.div
                        key={section.title}
                        initial={{ opacity: 0, y: 10 }}
                        animate={{ opacity: 1, y: 0 }}
                        transition={{ delay: globalI * 0.03, duration: 0.25 }}
                      >
                        <ReportSection
                          title={section.title}
                          content={section.content}
                          index={section.index}
                          defaultOpen={section.index <= 2}
                        />
                      </motion.div>
                    );
                  })}
                </div>
              </div>
            );
          })}
        </div>
      ) : (
        <div className="bg-white rounded-xl border border-slate-200 p-6">
          <pre className="whitespace-pre-wrap text-sm text-slate-700 leading-relaxed font-sans">
            {markdown}
          </pre>
        </div>
      )}

      {/* Footer */}
      <div className="flex items-center justify-between pt-1 pb-4">
        <p className="text-[11px] text-slate-400">
          Claims marked [ASSUMPTION] should be verified before use
        </p>
        <CopyButton text={markdown} label="Copy All" />
      </div>
    </div>
  );
}
