// GTM Report display — parses AI markdown into grouped section cards
"use client";

import { useMemo } from "react";
import { motion } from "framer-motion";
import { RefreshCw, CheckCircle2, AlertCircle } from "lucide-react";
import CopyButton from "./CopyButton";
import DownloadButton from "./DownloadButton";
import ReportSection from "./ReportSection";

interface GTMReportProps {
  markdown: string;
  onRegenerate: () => void;
}

interface ParsedSection {
  title: string;
  content: string;
  index: number;
}

interface SectionGroup {
  label: string;
  color: string;
  dot: string;
  indices: number[]; // 1-based section numbers in expected order
}

const SECTION_GROUPS: SectionGroup[] = [
  {
    label: "Market Strategy",
    color: "text-blue-600",
    dot: "bg-blue-500",
    indices: [1, 2, 3, 4, 5],
  },
  {
    label: "Messaging & Positioning",
    color: "text-violet-600",
    dot: "bg-violet-500",
    indices: [6, 7, 8, 9, 11],
  },
  {
    label: "Sales & Outreach Assets",
    color: "text-amber-600",
    dot: "bg-amber-500",
    indices: [12, 13, 14, 15],
  },
  {
    label: "Commercial & Action Plan",
    color: "text-emerald-600",
    dot: "bg-emerald-500",
    indices: [10, 16],
  },
];

// Pre-compute group index offsets once to avoid indexOf inside render loop
const GROUP_OFFSETS = SECTION_GROUPS.map((_, gi) =>
  SECTION_GROUPS.slice(0, gi).reduce((acc, g) => acc + g.indices.length, 0)
);

function parseMarkdownSections(markdown: string): ParsedSection[] {
  const lines = markdown.split("\n");
  const sections: ParsedSection[] = [];
  let currentTitle = "";
  let currentLines: string[] = [];
  let sectionIndex = 0;

  for (const line of lines) {
    // Match ## N. Title  OR  ## Title
    if (/^##\s/.test(line)) {
      if (currentTitle) {
        // Flush previous section — include even if content is empty
        sections.push({
          title: currentTitle,
          content: currentLines.join("\n").trim(),
          index: sectionIndex,
        });
      }
      const match = line.match(/^##\s+\d+\.\s+(.+)$/) || line.match(/^##\s+(.+)$/);
      sectionIndex++;
      currentTitle = match ? match[1].trim() : line.replace(/^##\s*/, "").trim();
      currentLines = [];
    } else if (currentTitle) {
      currentLines.push(line);
    }
  }

  // Flush the final section
  if (currentTitle) {
    sections.push({
      title: currentTitle,
      content: currentLines.join("\n").trim(),
      index: sectionIndex,
    });
  }

  return sections;
}

function MissingSection({ index }: { index: number }) {
  return (
    <div className="bg-white rounded-xl border border-slate-200 px-5 py-3.5 flex items-center gap-3">
      <div className="flex-shrink-0 w-7 h-7 rounded-lg bg-slate-100 flex items-center justify-center">
        <AlertCircle className="h-3.5 w-3.5 text-slate-300" />
      </div>
      <div className="flex items-center gap-2.5">
        <span className="text-[10px] font-bold text-slate-300 tabular-nums">
          {String(index).padStart(2, "0")}
        </span>
        <span className="text-[12px] text-slate-400 italic">
          Not found in generated report
        </span>
      </div>
    </div>
  );
}

export default function GTMReport({ markdown, onRegenerate }: GTMReportProps) {
  const sections = useMemo(() => parseMarkdownSections(markdown), [markdown]);

  const sectionByIndex = useMemo(() => {
    const map = new Map<number, ParsedSection>();
    sections.forEach((s) => map.set(s.index, s));
    return map;
  }, [sections]);

  return (
    <div className="space-y-3" id="workspace-report">
      {/* Report toolbar */}
      <div
        id="workspace-export"
        className="bg-white border border-slate-200 rounded-xl px-5 py-3.5 flex flex-col sm:flex-row sm:items-center justify-between gap-3"
      >
        <div className="flex items-center gap-3">
          <div className="w-7 h-7 rounded-full bg-emerald-100 flex items-center justify-center flex-shrink-0">
            <CheckCircle2 className="h-4 w-4 text-emerald-600" />
          </div>
          <div>
            <div className="flex items-center gap-2">
              <h2 className="text-sm font-semibold text-slate-900">
                GTM Pack Ready
              </h2>
              <span className="text-[11px] font-medium text-emerald-600 bg-emerald-50 border border-emerald-100 px-1.5 py-0.5 rounded-full">
                {sections.length} sections
              </span>
            </div>
            <p className="text-[11px] text-slate-500 mt-0.5">
              Generated by FinGTM Agent · Powered by DeepSeek · For strategic reference only
            </p>
          </div>
        </div>
        <div className="flex items-center gap-2 flex-wrap flex-shrink-0">
          <CopyButton text={markdown} label="Copy Report" />
          <DownloadButton content={markdown} filename="fingtm-report.md" />
          <button
            onClick={onRegenerate}
            className="inline-flex items-center gap-1.5 px-3 py-1.5 text-[12px] font-medium rounded-md border border-slate-200 bg-white text-slate-600 hover:bg-slate-50 hover:border-slate-300 transition-colors"
          >
            <RefreshCw className="h-3.5 w-3.5" />
            Regenerate
          </button>
        </div>
      </div>

      {/* Grouped section cards or raw fallback */}
      {sections.length > 0 ? (
        <div className="space-y-5">
          {SECTION_GROUPS.map((group, gi) => (
            <div key={group.label}>
              {/* Group header */}
              <div className="flex items-center gap-2 mb-2 px-1">
                <span className={`w-2 h-2 rounded-full flex-shrink-0 ${group.dot}`} />
                <span className={`text-[11px] font-bold uppercase tracking-widest ${group.color}`}>
                  {group.label}
                </span>
                <span className="flex-1 h-px bg-slate-200" />
                <span className="text-[10px] text-slate-500">
                  {group.indices.length} section{group.indices.length !== 1 ? "s" : ""}
                </span>
              </div>

              <div className="space-y-2">
                {group.indices.map((idx, i) => {
                  const section = sectionByIndex.get(idx);
                  const globalI = GROUP_OFFSETS[gi] + i;

                  if (!section) {
                    return <MissingSection key={idx} index={idx} />;
                  }

                  return (
                    <motion.div
                      key={section.title}
                      initial={{ opacity: 0, y: 10 }}
                      animate={{ opacity: 1, y: 0 }}
                      transition={{ delay: globalI * 0.03, duration: 0.25 }}
                    >
                      <ReportSection
                        title={section.title}
                        content={section.content}
                        index={section.index}
                        defaultOpen={section.index <= 2}
                      />
                    </motion.div>
                  );
                })}
              </div>
            </div>
          ))}
        </div>
      ) : (
        // Fallback: raw markdown when section parsing yields nothing
        <div className="bg-white rounded-xl border border-slate-200 p-6">
          <p className="text-[11px] text-slate-500 mb-4 flex items-center gap-1.5">
            <AlertCircle className="h-3.5 w-3.5 text-amber-400" />
            Section parsing did not match expected format. Showing full report below.
          </p>
          <pre className="whitespace-pre-wrap text-sm text-slate-700 leading-relaxed font-sans">
            {markdown}
          </pre>
        </div>
      )}

      {/* Footer */}
      <div className="flex items-center justify-between pt-1 pb-4">
        <p className="text-[11px] text-slate-500">
          Claims marked [ASSUMPTION] should be verified before use
        </p>
        <CopyButton text={markdown} label="Copy All" />
      </div>
    </div>
  );
}
