// GTM Report display — parses markdown into sections and renders each as a card
"use client";

import { useMemo } from "react";
import { motion } from "framer-motion";
import { RefreshCw, CheckCircle } from "lucide-react";
import CopyButton from "./CopyButton";
import DownloadButton from "./DownloadButton";
import ReportSection from "./ReportSection";

interface GTMReportProps {
  markdown: string;
  onRegenerate: () => void;
}

interface ParsedSection {
  title: string;
  content: string;
  index: number;
}

function parseMarkdownSections(markdown: string): ParsedSection[] {
  const lines = markdown.split("\n");
  const sections: ParsedSection[] = [];
  let currentTitle = "";
  let currentLines: string[] = [];
  let sectionIndex = 0;

  for (const line of lines) {
    const h2Match = line.match(/^##\s+\d+\.\s+(.+)$/) || line.match(/^##\s+(.+)$/);
    if (h2Match && line.startsWith("## ")) {
      if (currentTitle && currentLines.length > 0) {
        sections.push({ title: currentTitle, content: currentLines.join("\n").trim(), index: sectionIndex });
      }
      sectionIndex++;
      currentTitle = h2Match[1].trim();
      currentLines = [];
    } else if (currentTitle) {
      currentLines.push(line);
    }
  }

  if (currentTitle && currentLines.length > 0) {
    sections.push({ title: currentTitle, content: currentLines.join("\n").trim(), index: sectionIndex });
  }

  return sections;
}

export default function GTMReport({ markdown, onRegenerate }: GTMReportProps) {
  const sections = useMemo(() => parseMarkdownSections(markdown), [markdown]);

  return (
    <div>
      {/* Toolbar */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 mb-4">
        <div className="flex items-center gap-2">
          <div className="w-5 h-5 rounded-full bg-emerald-500 flex items-center justify-center">
            <CheckCircle className="h-3 w-3 text-white" />
          </div>
          <div>
            <h2 className="text-sm font-bold text-slate-900">FinGTM Report</h2>
            <p className="text-xs text-slate-400">{sections.length} sections generated</p>
          </div>
        </div>

        <div className="flex items-center gap-2 flex-wrap">
          <CopyButton text={markdown} label="Copy Report" />
          <DownloadButton content={markdown} filename="fingtm-report.md" />
          <button
            onClick={onRegenerate}
            className="inline-flex items-center gap-1.5 px-3 py-1.5 text-sm font-medium rounded-md border border-slate-200 bg-white text-slate-600 hover:bg-slate-50 hover:text-slate-900 transition-colors"
          >
            <RefreshCw className="h-3.5 w-3.5" />
            New Report
          </button>
        </div>
      </div>

      {/* Sections */}
      {sections.length > 0 ? (
        <div className="space-y-3">
          {sections.map((section, i) => (
            <motion.div
              key={section.title}
              initial={{ opacity: 0, y: 12 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: i * 0.04, duration: 0.25 }}
            >
              <ReportSection
                title={section.title}
                content={section.content}
                index={section.index}
                defaultOpen={i < 3}
              />
            </motion.div>
          ))}
        </div>
      ) : (
        <div className="bg-white rounded-xl border border-slate-200 p-6">
          <pre className="whitespace-pre-wrap text-sm text-slate-700 leading-relaxed font-sans">
            {markdown}
          </pre>
        </div>
      )}

      <div className="mt-4 flex items-center justify-between">
        <p className="text-xs text-slate-400">
          Generated by FinGTM Agent · Powered by DeepSeek · For strategic reference only
        </p>
        <CopyButton text={markdown} label="Copy All" />
      </div>
    </div>
  );
}
